function C = coriolis_matrix(q1,q2,q3,dq1,dq2,dq3,r0,r1,r2,ell0,ell1,ell2,g,m1,m2,m3,Ix1,Iy1,Iz1,Ix2,Iy2,Iz2,Ix3,Iy3,Iz3)
%CORIOLIS_MATRIX
%    C = CORIOLIS_MATRIX(Q1,Q2,Q3,DQ1,DQ2,DQ3,R0,R1,R2,ELL0,ELL1,ELL2,G,M1,M2,M3,IX1,IY1,IZ1,IX2,IY2,IZ2,IX3,IY3,IZ3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-Nov-2020 18:30:17

t2 = cos(q2);
t3 = sin(q3);
t4 = q2+q3;
t5 = ell1.^2;
t6 = q2.*2.0;
t7 = q3.*2.0;
t8 = r1.^2;
t9 = r2.^2;
t10 = sin(t6);
t11 = cos(t4);
t12 = sin(t4);
t13 = q2+t4;
t17 = ell1.*m3.*r2.*t2;
t18 = t4.*2.0;
t14 = sin(t13);
t15 = Iy3.*t11;
t16 = Iz3.*t11;
t20 = sin(t18);
t21 = m3.*t9.*t11;
t22 = (Iy2.*t10)./2.0;
t23 = (Iz2.*t10)./2.0;
t26 = (m3.*t5.*t10)./2.0;
t27 = (m2.*t8.*t10)./2.0;
t19 = -t15;
t24 = ell1.*m3.*r2.*t14;
t25 = -t22;
t28 = (Iy3.*t20)./2.0;
t29 = (Iz3.*t20)./2.0;
t31 = (m3.*t9.*t20)./2.0;
t30 = -t28;
t32 = t16+t17+t19+t21;
t33 = dq1.*t12.*t32;
t34 = t23+t24+t25+t26+t27+t29+t30+t31;
t35 = dq1.*t34;
C = reshape([-dq2.*t34-dq3.*t12.*t32,t35,t33,-t35,-dq3.*ell1.*m3.*r2.*t3,dq2.*ell1.*m3.*r2.*t3,-t33,-ell1.*m3.*r2.*t3.*(dq2+dq3),0.0],[3,3]);
