function B = coupling_matrix(q1,q2,q3,dq1,dq2,dq3,r0,r1,r2,ell0,ell1,ell2,g,m1,m2,m3,Ix1,Iy1,Iz1,Ix2,Iy2,Iz2,Ix3,Iy3,Iz3)
%COUPLING_MATRIX
%    B = COUPLING_MATRIX(Q1,Q2,Q3,DQ1,DQ2,DQ3,R0,R1,R2,ELL0,ELL1,ELL2,G,M1,M2,M3,IX1,IY1,IZ1,IX2,IY2,IZ2,IX3,IY3,IZ3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-Nov-2020 18:30:17

B = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,3]);
