function dJe = ef_jacobian_dt(q1,q2,q3,dq1,dq2,dq3,r0,r1,r2,ell0,ell1,ell2,g,m1,m2,m3,Ix1,Iy1,Iz1,Ix2,Iy2,Iz2,Ix3,Iy3,Iz3)
%EF_JACOBIAN_DT
%    DJE = EF_JACOBIAN_DT(Q1,Q2,Q3,DQ1,DQ2,DQ3,R0,R1,R2,ELL0,ELL1,ELL2,G,M1,M2,M3,IX1,IY1,IZ1,IX2,IY2,IZ2,IX3,IY3,IZ3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-Nov-2020 18:30:18

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = dq2+dq3;
t9 = q2+q3;
t10 = dq1.*t2;
t11 = cos(t9);
t12 = dq1.*t5;
t13 = ell1.*t6;
t14 = sin(t9);
t15 = dq2.*ell1.*t3;
t16 = dq2.*t11;
t17 = dq3.*t11;
t18 = r2.*t14;
t19 = -t10;
t20 = t13+t18;
t21 = t16+t17;
t22 = r2.*t21;
t23 = t15+t22;
dJe = reshape([dq2.*t2.*t13+ell1.*t3.*t12+r2.*t3.*t4.*t12-r2.*t6.*t7.*t12+dq2.*r2.*t2.*t3.*t7+dq2.*r2.*t2.*t4.*t6+dq3.*r2.*t2.*t3.*t7+dq3.*r2.*t2.*t4.*t6,dq2.*t5.*t13+ell1.*t3.*t19+r2.*t6.*t7.*t10+r2.*t3.*t4.*t19+dq2.*r2.*t3.*t5.*t7+dq2.*r2.*t4.*t5.*t6+dq3.*r2.*t3.*t5.*t7+dq3.*r2.*t4.*t5.*t6,0.0,0.0,0.0,0.0,t5.*t23+t10.*t20,-t2.*t23+t12.*t20,dq2.*t13+dq2.*t18+dq3.*t18,t12,t19,0.0,t10.*t18+r2.*t5.*t8.*t11,t12.*t18-r2.*t2.*t8.*t11,t8.*t18,t12,t19,0.0],[6,3]);
