function fK = fwd_kinematics(q1,q2,q3,dq1,dq2,dq3,r0,r1,r2,ell0,ell1,ell2,g,m1,m2,m3,Ix1,Iy1,Iz1,Ix2,Iy2,Iz2,Ix3,Iy3,Iz3)
%FWD_KINEMATICS
%    FK = FWD_KINEMATICS(Q1,Q2,Q3,DQ1,DQ2,DQ3,R0,R1,R2,ELL0,ELL1,ELL2,G,M1,M2,M3,IX1,IY1,IZ1,IX2,IY2,IZ2,IX3,IY3,IZ3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-Nov-2020 18:30:18

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = q2+q3;
t6 = ell1.*t3;
t7 = cos(t5);
t8 = sin(t5);
t9 = r2.*t7;
t10 = t6+t9;
fK = reshape([t2,t4,0.0,0.0,-t4.*t7,t2.*t7,-t8,0.0,-t4.*t8,t2.*t8,t7,0.0,-t4.*t10,t2.*t10,ell0-r2.*t8-ell1.*sin(q2),1.0],[4,4]);
